[paths]
data_dir   = "E:/data_preprocessing/preprocessing_CHB_MIT_dataset/CHB-MIT_dataset_2"
output_dir = "E:/data_preprocessing/preprocessing_CHB_MIT_dataset/CHB-MIT_pre_dataset"
annotations_path = "E:/data_preprocessing/preprocessing_CHB_MIT_dataset/CHB-MIT_dataset_2/all_seizures_info.csv"

[preprocessing]
picked_channels = ["FP1-F7", "F7-T7", "T7-P7", "P7-O1",
                     "FP1-F3", "F3-C3", "C3-P3", "P3-O1",
                     "FP2-F4", "F4-C4", "C4-P4", "P4-O2",
                     "FP2-F8", "F8-T8", "T8-P8-0", "P8-O2",
                     "FZ-CZ", "CZ-PZ", "T7-FT9", "FT9-FT10", "FT10-T8"]
channel_positions = [[-35.0, 58.0, 12.0], [-57.0, 34.0, 17.0], [-63.0, 7.0, 22.0], [-57.0, -22.0, 22.0],
                     [-15.0, 57.0, 10.0], [-35.0, 39.0, 21.0], [-40.0, 9.0, 25.0], [-45.0, -22.0, 24.0],
                     [15.0, 57.0, 10.0], [35.0, 39.0, 21.0], [40.0, 9.0, 25.0], [45.0, -22.0, 24.0],
                     [35.0, 58.0, 12.0], [57.0, 34.0, 17.0], [63.0, 7.0, 22.0], [57.0, -22.0, 22.0],
                     [0.0, 39.0, 22.0], [0.0, 9.0, 25.0], [-75.0, -1.0, 27.5], [0.0, 0.0, 70.0], [75.0, -1.0, 27.5]]
# Segmentation settings
first_segment_duration = 30  # Initial segment length (e.g., 30s pre-seizure)
second_segment_duration = 20 # Final retained segment length
# ICA settings
artifact_epoch_duration = 2
ICA_components = 16
# Epoch export settings
output_epoch_duration = 1
overlap_present = 0  # Overlap between epochs
# Automated artifact rejection (recommended for epilepsy data)
interactive = true
# Parallel processing (enable when no interaction needed)
parallel = false

